In [1]:
import pandas as pd
import os

# Path to the cleaned dataset
csv_path = "../02_Cleaned_Data/breast_cancer_cleaned.csv"

# Verify the file exists
if not os.path.exists(csv_path):
    raise FileNotFoundError(f"Dataset not found: {csv_path}")

# Extract the data
df = pd.read_csv(csv_path)

print("Dataset extracted successfully!")
print("Dataset shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

Dataset extracted successfully!
Dataset shape: (286, 16)

Column names:
['Class', 'Age', 'Tumor-Size', 'Inv-Nodes', 'Node-Caps', 'Deg-Malig', 'Breast', 'Irradiat', 'Menopause_ge40', 'Menopause_lt40', 'Menopause_premeno', 'Breast-Quad_central', 'Breast-Quad_left_low', 'Breast-Quad_left_up', 'Breast-Quad_right_low', 'Breast-Quad_right_up']

In [2]:
import os

print("Current working directory:")
print(os.getcwd())

print("\nCSV files in the cleaned data folder:")
print(os.listdir("../02_Cleaned_Data"))

Current working directory:
c:\Users\WINDOWS 11\Desktop\Breast_Cancer_Project\03_Notebooks

CSV files in the cleaned data folder:
['breast_cancer_cleaned.csv']

In [3]:
import pandas as pd

csv_path = "../02_Cleaned_Data/breast_cancer_cleaned.csv"
df = pd.read_csv(csv_path)

print("Loaded file:", os.path.abspath(csv_path))
print("Shape:", df.shape)
print("Duplicate rows:", df.duplicated().sum())

Loaded file: c:\Users\WINDOWS 11\Desktop\Breast_Cancer_Project\02_Cleaned_Data\breast_cancer_cleaned.csv
Shape: (286, 16)
Duplicate rows: 14

In [4]:
import pandas as pd

# Load the current cleaned-data file
csv_path = "../02_Cleaned_Data/breast_cancer_cleaned.csv"
df = pd.read_csv(csv_path)

print("Before cleaning:", df.shape)
print("Duplicate rows:", df.duplicated().sum())

# Remove exact duplicate records
df = df.drop_duplicates().reset_index(drop=True)

# Save the corrected cleaned dataset
df.to_csv(csv_path, index=False)

print("\nAfter cleaning:", df.shape)
print("Remaining duplicates:", df.duplicated().sum())
print("Missing values:", df.isnull().sum().sum())

Before cleaning: (286, 16)
Duplicate rows: 14

After cleaning: (272, 16)
Remaining duplicates: 0
Missing values: 0

In [5]:
import pandas as pd

df = pd.read_csv("../02_Cleaned_Data/breast_cancer_cleaned.csv")

print("Dataset shape:", df.shape)
print("Duplicate rows:", df.duplicated().sum())
print("Missing values:", df.isnull().sum().sum())

Dataset shape: (272, 16)
Duplicate rows: 0
Missing values: 0

In [6]:
import sqlite3
import os

db_path = "../04_Data_Warehouse/breast_cancer_warehouse.db"

if not os.path.exists(db_path):
    raise FileNotFoundError(f"Warehouse database not found: {db_path}")

conn = sqlite3.connect(db_path)
cursor = conn.cursor()

cursor.execute("""
    SELECT name
    FROM sqlite_master
    WHERE type = 'table'
      AND name NOT LIKE 'sqlite_%'
    ORDER BY name;
""")

tables = cursor.fetchall()

print("Warehouse tables:")
for table in tables:
    print("-", table[0])

conn.close()

Warehouse tables:
- Dim_Clinical
- Dim_Diagnosis
- Dim_Location
- Dim_Patient
- Dim_Tumor
- Fact_Breast_Cancer

In [7]:
import sqlite3

db_path = "../04_Data_Warehouse/breast_cancer_warehouse.db"

conn = sqlite3.connect(db_path)
cursor = conn.cursor()

tables = [
    "Dim_Patient",
    "Dim_Tumor",
    "Dim_Clinical",
    "Dim_Location",
    "Dim_Diagnosis",
    "Fact_Breast_Cancer"
]

for table in tables:
    print(f"\n--- {table} ---")
    cursor.execute(f"PRAGMA table_info({table})")

    for column in cursor.fetchall():
        print(f"Column: {column[1]}, Type: {column[2]}, Primary Key: {column[5]}")

conn.close()

--- Dim_Patient ---
Column: Patient_Key, Type: INTEGER, Primary Key: 1
Column: Age, Type: REAL, Primary Key: 0
Column: Breast, Type: INTEGER, Primary Key: 0
Column: Menopause_ge40, Type: INTEGER, Primary Key: 0
Column: Menopause_lt40, Type: INTEGER, Primary Key: 0
Column: Menopause_premeno, Type: INTEGER, Primary Key: 0

--- Dim_Tumor ---
Column: Tumor_Key, Type: INTEGER, Primary Key: 1
Column: Tumor_Size, Type: REAL, Primary Key: 0
Column: Inv_Nodes, Type: REAL, Primary Key: 0
Column: Node_Caps, Type: INTEGER, Primary Key: 0
Column: Deg_Malig, Type: INTEGER, Primary Key: 0

--- Dim_Clinical ---
Column: Clinical_Key, Type: INTEGER, Primary Key: 1
Column: Irradiat, Type: INTEGER, Primary Key: 0

--- Dim_Location ---
Column: Location_Key, Type: INTEGER, Primary Key: 1
Column: Breast_Quad_central, Type: INTEGER, Primary Key: 0
Column: Breast_Quad_left_low, Type: INTEGER, Primary Key: 0
Column: Breast_Quad_left_up, Type: INTEGER, Primary Key: 0
Column: Breast_Quad_right_low, Type: INTEGER, Primary Key: 0
Column: Breast_Quad_right_up, Type: INTEGER, Primary Key: 0

--- Dim_Diagnosis ---
Column: Diagnosis_Key, Type: INTEGER, Primary Key: 1
Column: Class, Type: INTEGER, Primary Key: 0

--- Fact_Breast_Cancer ---
Column: Fact_Key, Type: INTEGER, Primary Key: 1
Column: Patient_Key, Type: INTEGER, Primary Key: 0
Column: Tumor_Key, Type: INTEGER, Primary Key: 0
Column: Clinical_Key, Type: INTEGER, Primary Key: 0
Column: Location_Key, Type: INTEGER, Primary Key: 0
Column: Diagnosis_Key, Type: INTEGER, Primary Key: 0
Column: Patient_Count, Type: INTEGER, Primary Key: 0

In [8]:
import pandas as pd

csv_path = "../02_Cleaned_Data/breast_cancer_cleaned.csv"
df = pd.read_csv(csv_path)

print("Dataset columns:")
for col in df.columns:
    print("-", col)

print("\nFirst 5 records:")
display(df.head())

print("\nData types:")
print(df.dtypes)

Dataset columns:
- Class
- Age
- Tumor-Size
- Inv-Nodes
- Node-Caps
- Deg-Malig
- Breast
- Irradiat
- Menopause_ge40
- Menopause_lt40
- Menopause_premeno
- Breast-Quad_central
- Breast-Quad_left_low
- Breast-Quad_left_up
- Breast-Quad_right_low
- Breast-Quad_right_up

First 5 records:

,Class,Age,Tumor-Size,Inv-Nodes,Node-Caps,Deg-Malig,Breast,Irradiat,Menopause_ge40,Menopause_lt40,Menopause_premeno,Breast-Quad_central,Breast-Quad_left_low,Breast-Quad_left_up,Breast-Quad_right_low,Breast-Quad_right_up
0,0,34.5,32.0,1.0,0,3,0,0,0,0,1,0,1,0,0,0
1,0,44.5,22.0,1.0,0,2,1,0,0,0,1,0,0,0,0,1
2,0,44.5,22.0,1.0,0,2,0,0,0,0,1,0,1,0,0,0
3,0,64.5,17.0,1.0,0,2,1,0,1,0,0,0,0,1,0,0
4,0,44.5,2.0,1.0,0,2,1,0,0,0,1,0,0,0,1,0

Data types:
Class                      int64
Age                      float64
Tumor-Size               float64
Inv-Nodes                float64
Node-Caps                  int64
Deg-Malig                  int64
Breast                     int64
Irradiat                   int64
Menopause_ge40             int64
Menopause_lt40             int64
Menopause_premeno          int64
Breast-Quad_central        int64
Breast-Quad_left_low       int64
Breast-Quad_left_up        int64
Breast-Quad_right_low      int64
Breast-Quad_right_up       int64
dtype: object

In [9]:
# Source CSV column -> Warehouse dimension column mapping

dimension_mapping = {
    "Dim_Patient": {
        "Age": "Age",
        "Breast": "Breast",
        "Menopause_ge40": "Menopause_ge40",
        "Menopause_lt40": "Menopause_lt40",
        "Menopause_premeno": "Menopause_premeno"
    },
    "Dim_Tumor": {
        "Tumor-Size": "Tumor_Size",
        "Inv-Nodes": "Inv_Nodes",
        "Node-Caps": "Node_Caps",
        "Deg-Malig": "Deg_Malig"
    },
    "Dim_Clinical": {
        "Irradiat": "Irradiat"
    },
    "Dim_Location": {
        "Breast-Quad_central": "Breast_Quad_central",
        "Breast-Quad_left_low": "Breast_Quad_left_low",
        "Breast-Quad_left_up": "Breast_Quad_left_up",
        "Breast-Quad_right_low": "Breast_Quad_right_low",
        "Breast-Quad_right_up": "Breast_Quad_right_up"
    },
    "Dim_Diagnosis": {
        "Class": "Class"
    }
}

# Validate the source columns
source_columns = set(df.columns)
mapped_columns = {
    col
    for mapping in dimension_mapping.values()
    for col in mapping.keys()
}

print("Source columns:", len(source_columns))
print("Mapped source columns:", len(mapped_columns))
print("Unmapped columns:", source_columns - mapped_columns)
print("Missing source columns:", mapped_columns - source_columns)

if source_columns == mapped_columns:
    print("\nSUCCESS: All source columns are mapped.")
else:
    print("\nCHECK REQUIRED: The mapping does not match the source columns.")

Source columns: 16
Mapped source columns: 16
Unmapped columns: set()
Missing source columns: set()

SUCCESS: All source columns are mapped.

In [10]:
# Transform source data into dimension tables

# 1. Patient dimension
dim_patient = df[
    ["Age", "Breast", "Menopause_ge40",
     "Menopause_lt40", "Menopause_premeno"]
].drop_duplicates().reset_index(drop=True)

dim_patient.insert(0, "Patient_Key", range(1, len(dim_patient) + 1))


# 2. Tumor dimension
dim_tumor = df[
    ["Tumor-Size", "Inv-Nodes", "Node-Caps", "Deg-Malig"]
].drop_duplicates().reset_index(drop=True)

dim_tumor = dim_tumor.rename(columns={
    "Tumor-Size": "Tumor_Size",
    "Inv-Nodes": "Inv_Nodes",
    "Node-Caps": "Node_Caps",
    "Deg-Malig": "Deg_Malig"
})

dim_tumor.insert(0, "Tumor_Key", range(1, len(dim_tumor) + 1))


# 3. Clinical dimension
dim_clinical = df[["Irradiat"]].drop_duplicates().reset_index(drop=True)
dim_clinical.insert(0, "Clinical_Key", range(1, len(dim_clinical) + 1))


# 4. Location dimension
location_cols = [
    "Breast-Quad_central",
    "Breast-Quad_left_low",
    "Breast-Quad_left_up",
    "Breast-Quad_right_low",
    "Breast-Quad_right_up"
]

dim_location = df[location_cols].drop_duplicates().reset_index(drop=True)

dim_location = dim_location.rename(columns={
    "Breast-Quad_central": "Breast_Quad_central",
    "Breast-Quad_left_low": "Breast_Quad_left_low",
    "Breast-Quad_left_up": "Breast_Quad_left_up",
    "Breast-Quad_right_low": "Breast_Quad_right_low",
    "Breast-Quad_right_up": "Breast_Quad_right_up"
})

dim_location.insert(0, "Location_Key", range(1, len(dim_location) + 1))


# 5. Diagnosis dimension
dim_diagnosis = df[["Class"]].drop_duplicates().reset_index(drop=True)
dim_diagnosis.insert(0, "Diagnosis_Key", range(1, len(dim_diagnosis) + 1))


print("Dimension tables created successfully!")
print("Dim_Patient:", len(dim_patient), "records")
print("Dim_Tumor:", len(dim_tumor), "records")
print("Dim_Clinical:", len(dim_clinical), "records")
print("Dim_Location:", len(dim_location), "records")
print("Dim_Diagnosis:", len(dim_diagnosis), "records")

Dimension tables created successfully!
Dim_Patient: 19 records
Dim_Tumor: 86 records
Dim_Clinical: 2 records
Dim_Location: 5 records
Dim_Diagnosis: 2 records

In [12]:
# Build lookup dictionaries using consistent column names

# 1. Patient lookup
patient_cols = [
    "Age", "Breast", "Menopause_ge40",
    "Menopause_lt40", "Menopause_premeno"
]

patient_lookup = {
    tuple(row[c] for c in patient_cols): row["Patient_Key"]
    for _, row in dim_patient.iterrows()
}

# 2. Tumor lookup: use original source columns
tumor_cols = ["Tumor-Size", "Inv-Nodes", "Node-Caps", "Deg-Malig"]

tumor_lookup = {
    tuple(row[c] for c in tumor_cols): key
    for (_, row), key in zip(
        df[tumor_cols].drop_duplicates().iterrows(),
        dim_tumor["Tumor_Key"]
    )
}

# 3. Clinical lookup
clinical_lookup = dict(
    zip(dim_clinical["Irradiat"], dim_clinical["Clinical_Key"])
)

# 4. Location lookup: source names -> warehouse names
location_source_cols = [
    "Breast-Quad_central",
    "Breast-Quad_left_low",
    "Breast-Quad_left_up",
    "Breast-Quad_right_low",
    "Breast-Quad_right_up"
]

location_lookup = {
    tuple(row[c] for c in location_source_cols): key
    for (_, row), key in zip(
        df[location_source_cols].drop_duplicates().iterrows(),
        dim_location["Location_Key"]
    )
}

# 5. Diagnosis lookup
diagnosis_lookup = dict(
    zip(dim_diagnosis["Class"], dim_diagnosis["Diagnosis_Key"])
)

# Build fact table
fact = pd.DataFrame({
    "Fact_Key": range(1, len(df) + 1),

    "Patient_Key": [
        patient_lookup[tuple(row[c] for c in patient_cols)]
        for _, row in df.iterrows()
    ],

    "Tumor_Key": [
        tumor_lookup[tuple(row[c] for c in tumor_cols)]
        for _, row in df.iterrows()
    ],

    "Clinical_Key": df["Irradiat"].map(clinical_lookup),

    "Location_Key": [
        location_lookup[tuple(row[c] for c in location_source_cols)]
        for _, row in df.iterrows()
    ],

    "Diagnosis_Key": df["Class"].map(diagnosis_lookup),

    "Patient_Count": 1
})

print("Fact table created successfully!")
print("Fact table shape:", fact.shape)
print("\nMissing foreign keys:")
print(fact.isnull().sum())

display(fact.head())

Fact table created successfully!
Fact table shape: (272, 7)

Missing foreign keys:
Fact_Key         0
Patient_Key      0
Tumor_Key        0
Clinical_Key     0
Location_Key     0
Diagnosis_Key    0
Patient_Count    0
dtype: int64

,Fact_Key,Patient_Key,Tumor_Key,Clinical_Key,Location_Key,Diagnosis_Key,Patient_Count
0,1,1.0,1,1,1,1,1
1,2,2.0,2,1,2,1,1
2,3,3.0,2,1,1,1,1
3,4,4.0,3,1,3,1,1
4,5,2.0,4,1,4,1,1

In [13]:
# Validate fact table foreign-key relationships

checks = {
    "Patient_Key": set(dim_patient["Patient_Key"]),
    "Tumor_Key": set(dim_tumor["Tumor_Key"]),
    "Clinical_Key": set(dim_clinical["Clinical_Key"]),
    "Location_Key": set(dim_location["Location_Key"]),
    "Diagnosis_Key": set(dim_diagnosis["Diagnosis_Key"])
}

foreign_key_columns = {
    "Patient_Key": "Patient_Key",
    "Tumor_Key": "Tumor_Key",
    "Clinical_Key": "Clinical_Key",
    "Location_Key": "Location_Key",
    "Diagnosis_Key": "Diagnosis_Key"
}

all_valid = True

for fact_col, dimension_col in foreign_key_columns.items():
    invalid = set(fact[fact_col].dropna()) - checks[dimension_col]
    print(f"{fact_col}: {len(invalid)} invalid keys")

    if invalid:
        all_valid = False

print("\nAll foreign keys valid:", all_valid)
print("Fact records:", len(fact))
print("Expected records:", len(df))
print("Record count matches:", len(fact) == len(df))

Patient_Key: 0 invalid keys
Tumor_Key: 0 invalid keys
Clinical_Key: 0 invalid keys
Location_Key: 0 invalid keys
Diagnosis_Key: 0 invalid keys

All foreign keys valid: True
Fact records: 272
Expected records: 272
Record count matches: True

In [14]:
import sqlite3

db_path = "../04_Data_Warehouse/breast_cancer_warehouse.db"

conn = sqlite3.connect(db_path)
cursor = conn.cursor()

tables = [
    "Dim_Patient",
    "Dim_Tumor",
    "Dim_Clinical",
    "Dim_Location",
    "Dim_Diagnosis",
    "Fact_Breast_Cancer"
]

print("Existing warehouse record counts:\n")

for table in tables:
    cursor.execute(f"SELECT COUNT(*) FROM {table}")
    count = cursor.fetchone()[0]
    print(f"{table}: {count} records")

conn.close()

Existing warehouse record counts:

Dim_Patient: 0 records
Dim_Tumor: 0 records
Dim_Clinical: 0 records
Dim_Location: 0 records
Dim_Diagnosis: 0 records
Fact_Breast_Cancer: 0 records

In [15]:
import sqlite3

db_path = "../04_Data_Warehouse/breast_cancer_warehouse.db"

# Confirm the tables are still empty before loading
conn = sqlite3.connect(db_path)

try:
    cursor = conn.cursor()

    tables = [
        "Dim_Patient",
        "Dim_Tumor",
        "Dim_Clinical",
        "Dim_Location",
        "Dim_Diagnosis",
        "Fact_Breast_Cancer"
    ]

    for table in tables:
        cursor.execute(f"SELECT COUNT(*) FROM {table}")
        if cursor.fetchone()[0] != 0:
            raise RuntimeError(
                f"{table} is no longer empty. Loading cancelled."
            )

    # Enable foreign-key checking on this connection
    cursor.execute("PRAGMA foreign_keys = ON")

    # Load dimension tables first
    dim_patient.to_sql("Dim_Patient", conn, if_exists="append", index=False)
    dim_tumor.to_sql("Dim_Tumor", conn, if_exists="append", index=False)
    dim_clinical.to_sql("Dim_Clinical", conn, if_exists="append", index=False)
    dim_location.to_sql("Dim_Location", conn, if_exists="append", index=False)
    dim_diagnosis.to_sql("Dim_Diagnosis", conn, if_exists="append", index=False)

    # Load the fact table after its dimensions
    fact.to_sql("Fact_Breast_Cancer", conn, if_exists="append", index=False)

    # Verify foreign-key constraints
    cursor.execute("PRAGMA foreign_key_check")
    violations = cursor.fetchall()

    if violations:
        raise RuntimeError(f"Foreign-key violations found: {violations}")

    conn.commit()
    print("ETL LOAD SUCCESSFUL!")

except Exception as e:
    conn.rollback()
    print("ETL LOAD FAILED — transaction rolled back.")
    print("Error:", e)

finally:
    conn.close()

ETL LOAD SUCCESSFUL!

In [16]:
import sqlite3

db_path = "../04_Data_Warehouse/breast_cancer_warehouse.db"

conn = sqlite3.connect(db_path)
cursor = conn.cursor()

tables = [
    "Dim_Patient",
    "Dim_Tumor",
    "Dim_Clinical",
    "Dim_Location",
    "Dim_Diagnosis",
    "Fact_Breast_Cancer"
]

print("FINAL WAREHOUSE RECORD COUNTS\n")

for table in tables:
    cursor.execute(f"SELECT COUNT(*) FROM {table}")
    count = cursor.fetchone()[0]
    print(f"{table}: {count} records")

print("\nForeign-key violations:")
cursor.execute("PRAGMA foreign_key_check")
violations = cursor.fetchall()
print(violations)

conn.close()

FINAL WAREHOUSE RECORD COUNTS

Dim_Patient: 19 records
Dim_Tumor: 86 records
Dim_Clinical: 2 records
Dim_Location: 5 records
Dim_Diagnosis: 2 records
Fact_Breast_Cancer: 272 records

Foreign-key violations:
[]

In [17]:
import sqlite3

db_path = "../04_Data_Warehouse/breast_cancer_warehouse.db"

conn = sqlite3.connect(db_path)

query = """
SELECT d.Class, COUNT(*) AS Record_Count
FROM Fact_Breast_Cancer f
JOIN Dim_Diagnosis d
    ON f.Diagnosis_Key = d.Diagnosis_Key
GROUP BY d.Class
ORDER BY d.Class;
"""

print("Diagnosis distribution in warehouse:")
print(conn.execute(query).fetchall())

print("\nTotal patient count:")
print(conn.execute(
    "SELECT SUM(Patient_Count) FROM Fact_Breast_Cancer"
).fetchone()[0])

print("\nUnique fact keys:")
print(conn.execute(
    "SELECT COUNT(DISTINCT Fact_Key) FROM Fact_Breast_Cancer"
).fetchone()[0])

conn.close()

Diagnosis distribution in warehouse:
[(0, 191), (1, 81)]

Total patient count:
272

Unique fact keys:
272